# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: lint-ts
      name: "lint ts"
      entry: /usr/bin/env bash -c "npm run prettier:ts"
      files: '\.ts$'
      language: script
      description: "Checks TS code according to the package's linter configuration"
    - id: lint-sol
      name: "lint solidity"
      entry: /usr/bin/env bash -c "npm run lint:sol"
      files: '\.sol$'
      language: script
      description: "Checks Solidity code according to the package's linter configuration"
